spring.application.name=FullStackApplication1
spring.datasource.url = jdbc:postgresql://localhost:5432/studentData
spring.datasource.username = postgres
spring.datasource.password = postgres
spring.datasource.driveraClassName = org.postgresql.Driver
spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
